### ISSUE TITLE
Trying to understand how to input data into the network.

### ISSUE THREAD

**Issue by lingxiao** [tscheepers/hred-attention-tensorflow#3]
Hey everyone:

I am trying to run your code here:

https://github.com/tscheepers/hred-attention-tensorflow

as part of a project to benchmark your model. 

However, we are having some issue understanding what to do with out tokenized data. Specifically, we have a index to word dictionary where we have:

0: <pad>
1: <unk>
2: <go>
3: <eoq>
4: <eos>
etc.

Our training and validation data is saved as a .pkl file. It is a list of lists of integers, where the first dimension is the number of utterances in the conversation, and the second dimension is the number of words per utterance. For example, if we load it using `numpy.load('path/to/file.pkl')`.
we might see:

[[34  53     9 133     4],
[6 5653 322   45 133 4]]

which might decode to:

"hello how are you <eos>"
"I am great and you <eos>"

However, when we passed these into the Trainer object in train.py file, the Trainer appear to tokenize them in some odd manner. Specifically, when we train the model, the example outputs are just certain words repeated over and over again. 

I am wondering if you might give me some pointers please?

**Comment by toologicbv** [comment]
Hi,
It's unfortunately a while ago and detailed knowlegde about the pre-processing part is not really "present" anymore. But actually in the data directory you'll find examples of all the input files that are necessary to run the model and you can re-engineer your input to that (in the beginning of train.py the input files are specified). E.g. under data you'll find a small pickle file "aol_vocab_2500.pkl" that you can inspect. I think it contains 2 dictionaries, one with the transation word to index and one with the word frequencies. Under data/sordoni/dev you can find pickled examples of the input files we used. And check-out the readme in hred-attention-tensorflow/src/sordoni/ which gives more details on how to get started. hope this helps

**Comment by maartjeth** [comment]
I assume this issue was solved, but please feel free to reopen.
