### ISSUE TITLE
any guide to get start, and the dataset format?

### ISSUE THREAD

**Issue by loveJasmine** [tscheepers/hred-attention-tensorflow#4]

**Comment by moluxiaobei** [comment]
1、将原始数据转为pkl格式的训练数据和测试数据(convert-text2dict.py)  2.运行train.py，这里包括了数据batch处理以及sample-beam环节,准确率作为考量指标。3.运行search.py 或者score.py 得到分数和预测。  我这里的问题是在训练的时候发现sample的预测结果都是一样重复的，在排查原因，应该是哪里写错了

**Comment by moluxiaobei** [comment]
我认为train.py下beam_sample这个函数是错误的，attention_mask通过step_inference每次结果都是一样的，并没什么改变 导致接下来错误

**Comment by moluxiaobei** [comment]
Dear Author，Thank you for your work！
