### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by mouradyahia** [tscheepers/hred-attention-tensorflow#6]
Hello Thijs,

I found your implementation of your improved HRED model, and it looks very clear and well organized.
So I want to congratulate you on your work and to thank you for sharing it publicly.
I have been trying to reproduce your results with your code and data and I have seen all kinds of errors in the code.
Knowing the good quality of your code, I believe it's a Tensorflow version mismatch.
Can you please tell me the exact version you've carried out your work with?

Thank you in advance!

**Comment by maartjeth** [comment]
Hey there,
Not entirely sure anymore about the exact version tbh - but I guess it's been around 0.12.  
Hope that helps.
